#!/bin/bash
# Two-pass LTO+PGO release build, shared by every CI platform job.
#
# WHY: the CMake build already supports -flto (on by default) and PGO
# (PGO_GENERATE / PGO_USE), but CI historically passed -DDISABLE_LTO=ON and
# never ran PGO -- shipping binaries ~20% slower than a local LTO+PGO build
# (measured same-silicon: no-LTO/no-PGO 8.07 KH/s vs LTO+PGO 9.75 KH/s, +20.7%).
# This script restores both, identically across platforms, so Linux / AMD /
# HiveOS / Android match the Windows hashrate.
#
# Produces an LTO+PGO-optimized $TARGET under $BUILD_DIR/bin.
#
# Env knobs (all optional):
#   BUILD_DIR=build                  final build dir (binary lands in $BUILD_DIR/bin)
#   TARGET=dirtybird-c-miner       executable to produce
#   TRAIN_TARGET=dirtybird-c-pgo-train instrumented hashrate trainer
#   TRAIN_SECS=60                    trainer runtime for profile collection
#   TRAIN_THREADS=<nproc>            trainer threads
#   DIFFICULTY=1000000000            synthetic difficulty (pure hashrate, no shares)
#   PROFDATA=llvm-profdata           llvm-profdata binary (e.g. llvm-profdata-18)
#   TRAIN_RUNNER=""                  prefix to run trainer (e.g. "qemu-aarch64-static")
#   PGO_PROFILE_IN=""                use this prebuilt merged.profdata; skip gen+train
#                                    (for cross-compiled targets that can't run here)
#   PGO_PROFILE_OUT=""               if set, copy the merged profile here (export as artifact)
#   CMAKE_ARGS=""                    extra cmake args (toolchain file, OpenSSL root, -DDIRTYBIRD_C_VERSION=...)
#   GEN_CMAKE_ARGS=""                extra cmake args for the INSTRUMENT pass only
#                                    (e.g. -DCMAKE_EXE_LINKER_FLAGS=-static so a
#                                     cross trainer is self-contained and runs
#                                     under qemu/binfmt; the final build stays as
#                                     CMAKE_ARGS, i.e. normal dynamic linkage)
#   GENERATOR=Ninja
set -euo pipefail

BUILD_DIR="${BUILD_DIR:-build}"
TARGET="${TARGET:-dirtybird-c-miner}"
TRAIN_TARGET="${TRAIN_TARGET:-dirtybird-c-pgo-train}"
TRAIN_SECS="${TRAIN_SECS:-60}"
DIFFICULTY="${DIFFICULTY:-1000000000}"
PROFDATA="${PROFDATA:-llvm-profdata}"
TRAIN_RUNNER="${TRAIN_RUNNER:-}"
PGO_PROFILE_IN="${PGO_PROFILE_IN:-}"
PGO_PROFILE_OUT="${PGO_PROFILE_OUT:-}"
CMAKE_ARGS="${CMAKE_ARGS:-}"
GEN_CMAKE_ARGS="${GEN_CMAKE_ARGS:-}"
GENERATOR="${GENERATOR:-Ninja}"
TRAIN_THREADS="${TRAIN_THREADS:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4)}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# Resolve a possibly-.exe binary path (Windows MSYS2 vs Linux).
resolve_bin() { local b="$1"; if [ -f "$b.exe" ]; then echo "$b.exe"; else echo "$b"; fi; }

PROFILE=""
if [ -n "$PGO_PROFILE_IN" ]; then
  # Cross-compiled targets (Android) can't run the trainer here, so they pass a
  # prebuilt profile (generated by a matching-LLVM-major build elsewhere). No
  # llvm-profdata needed on this runner in that case.
  echo "[build-pgo] using prebuilt profile: $PGO_PROFILE_IN"
  PROFILE="$PGO_PROFILE_IN"
else
  # Resolve llvm-profdata to match the clang major version (Ubuntu ships it as
  # llvm-profdata-18, etc.). The profile reader must match the instrumenting clang.
  if ! command -v "$PROFDATA" >/dev/null 2>&1; then
    CLANG_MAJ="$(clang --version 2>/dev/null | grep -oE 'version [0-9]+' | grep -oE '[0-9]+' | head -1 || true)"
    if [ -n "${CLANG_MAJ:-}" ] && command -v "llvm-profdata-${CLANG_MAJ}" >/dev/null 2>&1; then
      PROFDATA="llvm-profdata-${CLANG_MAJ}"
    fi
  fi
  command -v "$PROFDATA" >/dev/null 2>&1 || { echo "[build-pgo] ERROR: llvm-profdata not found (tried '$PROFDATA')" >&2; exit 3; }
  echo "[build-pgo] using profdata: $PROFDATA"
  GEN_DIR="${BUILD_DIR}-pgo-gen"
  echo "[build-pgo] pass 1/2: instrumented trainer ($GEN_DIR)"
  # Keep LTO ON for the instrumented build. It pulls in -fuse-ld=lld, which is
  # required: mingw GNU ld drops the PGO counter COMDATs (__profc_/__profd_) for
  # inline/template functions and the link fails with undefined references; lld
  # resolves them. (LTO also keeps Linux gen consistent with the use build.)
  cmake -S . -B "$GEN_DIR" -G "$GENERATOR" -DCMAKE_BUILD_TYPE=Release \
    -DPGO_GENERATE=ON $CMAKE_ARGS $GEN_CMAKE_ARGS
  cmake --build "$GEN_DIR" --target "$TRAIN_TARGET" --parallel
  TRAIN_BIN="$(resolve_bin "$GEN_DIR/bin/$TRAIN_TARGET")"
  echo "[build-pgo] collecting profile: ${TRAIN_SECS}s @ ${TRAIN_THREADS}t (runner='${TRAIN_RUNNER}')"
  ( cd "$GEN_DIR/bin" && rm -f ./*.profraw && \
    LLVM_PROFILE_FILE="pgo-%p.profraw" $TRAIN_RUNNER "./$(basename "$TRAIN_BIN")" \
      -t "$TRAIN_THREADS" --seconds "$TRAIN_SECS" --difficulty "$DIFFICULTY" --rotate-ms 5000 )
  # Merge from inside bin/ with relative paths: a native (non-MSYS) llvm-profdata
  # on Windows cannot open /c/.. style MSYS paths, so avoid passing them.
  ( cd "$GEN_DIR/bin" && "$PROFDATA" merge -o merged.profdata ./*.profraw )
  PROFILE="$ROOT/$GEN_DIR/bin/merged.profdata"
  echo "[build-pgo] profile: $(wc -c < "$PROFILE") bytes"
fi

if [ -n "$PGO_PROFILE_OUT" ]; then
  mkdir -p "$(dirname "$PGO_PROFILE_OUT")"
  cp "$PROFILE" "$PGO_PROFILE_OUT"
  echo "[build-pgo] exported profile -> $PGO_PROFILE_OUT"
fi

# Native cmake/clang on Windows need a Windows-style path (F:/..), not MSYS /f/..
PROFILE_ARG="$PROFILE"
if command -v cygpath >/dev/null 2>&1; then PROFILE_ARG="$(cygpath -m "$PROFILE")"; fi

echo "[build-pgo] pass 2/2: LTO+PGO build ($BUILD_DIR) [profile: $PROFILE_ARG]"
cmake -S . -B "$BUILD_DIR" -G "$GENERATOR" -DCMAKE_BUILD_TYPE=Release \
  -DPGO_USE=ON -DPGO_PROFILE="$PROFILE_ARG" $CMAKE_ARGS
cmake --build "$BUILD_DIR" --target "$TARGET" --parallel
echo "[build-pgo] done: $BUILD_DIR/bin/$TARGET (LTO+PGO)"
